[package]
name = "ping_pong"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
actorlib = {path = "../../lib"}
futures = "0.3.26"

env_logger = "0.10.0"
log = "0.4.17"

tokio = { version = "1.25.0", features = ["full"] }

